#define Vatorex_VERSION_MAJOR 3
#define Vatorex_VERSION_MINOR 4

/* #undef MITE_TRUTH */
/* #undef BUILD_DEV_GUI_ACTIVE */
/* #undef DONT_KEEP_DETAIL_IMAGES */
/* #undef BUILD_CANDIATE_COLLECTOR */
/* #undef BUILD_COUNTER_APP */
#define DONT_USE_FILESYSTEM
/* #undef LOG_TO_FILE */
/* #undef LOG_TO_COUT */
#define LOG_ON_DEMAND
/* #undef RENDER_ELLIPSE_ON_CANDS */
#define HSL_HIST_FOR_CANDS
#define HIST_FOR_CONTEXT
#define REFINE_CANDS
/* #undef SHARPENESS_ALLWAYS_SUBDIVIDED */
/* #undef DONT_RESCALE_EXTRATED_MITE_CANDS */
#define MULTITHREADED_COUNT

/* #undef LGBM_PATH */
/* #undef LGBM_MODEL */
/* #undef TEST_IMAGE_PATH */
